//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2work
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database1Entities1 : DbContext
    {
        public Database1Entities1()
            : base("name=Database1Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<x74jp_advisers> x74jp_advisers { get; set; }
        public virtual DbSet<x74jp_appointement> x74jp_appointement { get; set; }
        public virtual DbSet<x74jp_company> x74jp_company { get; set; }
        public virtual DbSet<x74jp_documents> x74jp_documents { get; set; }
        public virtual DbSet<x74jp_organization> x74jp_organization { get; set; }
        public virtual DbSet<x74jp_registered> x74jp_registered { get; set; }
        public virtual DbSet<x74jp_userTypes> x74jp_userTypes { get; set; }
    }
}
