//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2work
{
    using System;
    using System.Collections.Generic;
    
    public partial class x74jp_appointement
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public System.DateTime time { get; set; }
        public string objet { get; set; }
        public int id_x74jp_registered { get; set; }
    
        public virtual x74jp_registered x74jp_registered { get; set; }
    }
}
